module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './lib/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      one: '#7c5dfa',
      two: '#9277ff',
      three: '#1e2139',
      four: '#252945',
      five: '#dfe3fa',
      six: '#888eb0',
      seven: '#7e88c3',
      eight: '#0c0e16',
      nine: '#ec5757',
      ten: '#ff9797',
      eleven: '#f8f8fb',
      twelve: '#141625',
      white: '#ffffff',
      black: '#000000',
      green: '#33d69f',
      orange: '#ff8f00',
      darkGray: '#373b53',
      buttonLight: '#f9fafe',
      gradient: 'rgba(0, 0, 0, 0.5)',
    },
    lineHeight: {
      zero: '0',
      normal: '1.5',
      medium: '1.6',
      large: '1.8',
    },
    extend: {},
  },
  plugins: [],
};
